"""
PyTorch dataset for loading preprocessed fundus images
paired with their grade-conditioned text prompts.

Works with both APTOS 2019 and EyePACS preprocessed data.
"""

from pathlib import Path

import pandas as pd
import torch
from PIL import Image
from torch.utils.data import Dataset
from torchvision import transforms

from src.data.prompt_registry import get_prompt


class EyePACSDataset(Dataset):
    """
    Loads preprocessed fundus images and pairs them with text prompts
    based on DR grade. Used for both LoRA fine-tuning (with prompts)
    and downstream classification (grade labels only).
    """

    def __init__(
        self,
        manifest_csv: str,
        image_size: int = 512,
        mode: str = "diffusion",
        grades: list[int] | None = None,
    ):
        """
        Args:
            manifest_csv: Path to the preprocessing manifest CSV.
            image_size: Target image size.
            mode: "diffusion" returns (image, prompt) pairs for SD training.
                  "classification" returns (image, grade) pairs for downstream eval.
            grades: If set, only include images from these DR grades.
        """
        self.manifest = pd.read_csv(manifest_csv)
        self.mode = mode
        self.image_size = image_size

        if grades is not None:
            self.manifest = self.manifest[
                self.manifest["grade"].isin(grades)
            ].reset_index(drop=True)

        if mode == "diffusion":
            self.transform = transforms.Compose([
                transforms.Resize(image_size, interpolation=transforms.InterpolationMode.LANCZOS),
                transforms.CenterCrop(image_size),
                transforms.ToTensor(),
                transforms.Normalize([0.5], [0.5]),
            ])
        else:
            # Standard ImageNet normalization for classification
            self.transform = transforms.Compose([
                transforms.Resize(256),
                transforms.CenterCrop(224),
                transforms.ToTensor(),
                transforms.Normalize(
                    mean=[0.485, 0.456, 0.406],
                    std=[0.229, 0.224, 0.225],
                ),
            ])

    def __len__(self) -> int:
        return len(self.manifest)

    def __getitem__(self, idx: int) -> dict:
        row = self.manifest.iloc[idx]
        img = Image.open(row["image_path"]).convert("RGB")
        img = self.transform(img)
        grade = int(row["grade"])

        if self.mode == "diffusion":
            return {
                "pixel_values": img,
                "prompt": get_prompt(grade),
                "grade": grade,
            }
        else:
            return {
                "pixel_values": img,
                "grade": grade,
            }


class SyntheticFundusDataset(Dataset):
    """
    Loads synthetic fundus images generated by MedFuse.
    Used during the downstream augmentation experiments.
    """

    def __init__(self, synthetic_dir: str, image_size: int = 224):
        self.image_paths = []
        self.grades = []

        synthetic_path = Path(synthetic_dir)
        for grade_dir in sorted(synthetic_path.iterdir()):
            if not grade_dir.is_dir() or not grade_dir.name.startswith("grade_"):
                continue
            grade = int(grade_dir.name.split("_")[1])
            for img_file in sorted(grade_dir.glob("*.png")):
                self.image_paths.append(str(img_file))
                self.grades.append(grade)

        self.transform = transforms.Compose([
            transforms.Resize(256),
            transforms.CenterCrop(image_size),
            transforms.ToTensor(),
            transforms.Normalize(
                mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225],
            ),
        ])

    def __len__(self) -> int:
        return len(self.image_paths)

    def __getitem__(self, idx: int) -> dict:
        img = Image.open(self.image_paths[idx]).convert("RGB")
        img = self.transform(img)
        return {
            "pixel_values": img,
            "grade": self.grades[idx],
        }
